# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-14 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_auto_20151213_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sitelink',
            old_name='link_html',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='sitelink',
            old_name='link_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='sitelink',
            old_name='link_text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='sitelink',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_vote',
            field=models.IntegerField(default=0),
        ),
    ]
