# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-14 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_auto_20160714_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteLink',
            new_name='Link',
        ),
    ]
