# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_auto_20160714_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
