# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_link_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-pub_date']},
        ),
    ]
