# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_auto_20160715_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='pub_date',
            field=models.DateTimeField(default=b'2011-09-01T13:20:30+03:00'),
        ),
    ]
