# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_auto_20160715_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
